### ISSUE TITLE
Configuration to Never suspen when plugged in have no effect

### ISSUE THREAD

**Issue by snaggen** [pop-os/cosmic-idle#9]
Using latest Fedora packages from copr (should be nightly built), and I have configured "Automatic suspend when plugged in: Never" in cosmic-settings. The laptop is still suspended. I don't know how long it did idle before it got suspended, since I wasn't in the room. But the journalctl clearly shows that it suspended:
```
nov 06 09:50:35 locke systemd[1]: Starting systemd-suspend.service - System Suspend...
```

**Comment by snaggen** [comment]
Looking at the code, I don't understand how we get to the suspend.... I'm trying to set the on battery suspend to never and see if that will prohibit the suspention... but that is also not very likely if I look at the code... but hey, it seems we are in the unlikely territory here...

**Comment by snaggen** [comment]
upower reports on-battery: no, so the battery setting shouldn't have any effect.... but we will see anyway...

**Comment by snaggen** [comment]
@ids1024 Looking at the code i notice that the initial state will have on_battery = false. In the case where I start my laptop on battery, will it get an OnBattery notification or how does that work? 

Note: Not relevant to my issue here really, since it would ensure that it uses the on ac settings... just something I noticed and got a bit confused about.

**Comment by l-const** [comment]
Hey, @snaggen you do get events that change the value, see here: https://github.com/pop-os/cosmic-idle/blob/master/src/main.rs#L64-L67 , https://github.com/pop-os/cosmic-idle/blob/master/src/main.rs#L209-L211

**Comment by snaggen** [comment]
I don't know since there aren't really any logs for those events from what I can see

**Comment by snaggen** [comment]
I have added some debug to clearly see what is happening, and also commented out the 'systemctl suspend' call. And I still get suspends. I have changed the timing of the screen blanking, and it seems that when ever the screen is fading to black the system also goes to suspend. This is not explicitly done by cosmic-idle. I can see that the code path is that it will correctly get a idle notification and run the 
```
            state.update_screen_off_idle(is_idle);
``` 
as expected. 

Still , the system goes to suspend. 
So, I wonder if there is some DPMS issue causing the FadeBlackSurface to trigger a suspend. Not sure if this would be a bug in the DPMS code, or just some magic Fedora suspend handling...

**Comment by ids1024** [comment]
> Looking at the code i notice that the initial state will have on_battery = false. In the case where I start my laptop on battery, will it get an OnBattery notification or how does that work?

Yes, if the `UPower` daemon is running when `cosmic-idle` starts, it will get an initial event and update that based on whether or not `UPower` says the device is on battery. If `UPower` isn't running, it will stick with the default and assume it's on AC (or has no battery).

> I have added some debug to clearly see what is happening, and also commented out the 'systemctl suspend' call. And I still get suspends. I have changed the timing of the screen blanking, and it seems that when ever the screen is fading to black the system also goes to suspend.

Huh. So it doesn't suspend if you remove the `.set_mode(zwlr_output_power_v1::Mode::Off);` line?

If so, yeah, that's pretty odd. I guess it could be some firmware/driver weirdness. But I guess then Gnome would have the same issue?

**Comment by snaggen** [comment]
I will try to remove that line and see... but that will be tomorrow

**Comment by l-const** [comment]
doesn't  `on_battery` variable change for laptops when plugged in and out of AC? if the var is set only on startup, maybe an enhancement is needed??

**Comment by snaggen** [comment]
It is set on events. I just didn't know that you would get an on battery event when you initially connect to the upowerd. So, the code looked strange to me...

**Comment by l-const** [comment]
Still, it is probably wrong the way it is because there are two different timeouts and the state of the machine whether it is on power or not should adhear to the different timeout, for example when you connect your laptop to AC you would want to suspend/blank the screen at a greater timeout than when on battery, but if you laptop was running on battery on startup that won't happen. And to be honest, when the on_battery changes that means that we had an interaction with the system so the notification timer should reset.

**Comment by snaggen** [comment]
> > Looking at the code i notice that the initial state will have on_battery = false. In the case where I start my laptop on battery, will it get an OnBattery notification or how does that work?
> 
> Yes, if the `UPower` daemon is running when `cosmic-idle` starts, it will get an initial event and update that based on whether or not `UPower` says the device is on battery. If `UPower` isn't running, it will stick with the default and assume it's on AC (or has no battery).
> 
> > I have added some debug to clearly see what is happening, and also commented out the 'systemctl suspend' call. And I still get suspends. I have changed the timing of the screen blanking, and it seems that when ever the screen is fading to black the system also goes to suspend.
> 
> Huh. So it doesn't suspend if you remove the `.set_mode(zwlr_output_power_v1::Mode::Off);` line?
> 
> If so, yeah, that's pretty odd. I guess it could be some firmware/driver weirdness. But I guess then Gnome would have the same issue?

If I remove the line above it doesn't go to suspend. Then it just fades to black, and go to the lock screen. So that line triggers something causing a suspend.
I see the line
```
nov 06 21:31:15 locke systemd-logind[1145]: Suspending...
``` 
in the journalctl logs. It is the first suspend related log after the cosmic idle log line I have added. So it seems that it might be logind that reacts to something... not sure. This is a bit outside my expertise.

**Comment by ids1024** [comment]
Logind might suspend because another program has instructed it to. Or logind can do some things automatically, configured in `/etc/systemd/logind.conf`. But I don't think DPMS off should be a condition it handles...

**Comment by snaggen** [comment]
I did check the /etc/systemd/logind.conf, but that is blank so it just uses default and then the idle action should be nothing. Also, it doesn't have its own timer (which would be the case if it was logind acting on its own), it reacts to the cosmic-idle dpms... so it is just weird.

**Comment by snaggen** [comment]
Just switched back to Gnome to test this, and there my laptop doesn't suspend when the screens are turned off.
The screens report "No Signal" and say that it will go to energy saving mode in one minute. Not sure if that is any indication that Gnome isn't fully turning off the screen... this is out of my expertise.

**Comment by snaggen** [comment]
Not sure what have changed and where, but now I realize that my laptop doesn't suspend anymore. So, it seems this issue is fixed, either by something in cosmic or fedora.

**Comment by jwaga** [comment]
Still the case on my machine. Below AI - generated summary of the investigation:

---

Still seeing this on Pop!_OS 24.04 / COSMIC (`cosmic-idle` `0.1.0~…c95d066`).

**Setup:** auto-suspend on AC = Never (`suspend_on_ac_time = None`), on battery = 30 min. Lid/power-key handled separately.

**What happens:** After idle (~30 min) the machine suspends even while on AC. Journal shows user-initiated suspend (`OPERATOR=<user>`, `systemctl suspend` path), consistent with `cosmic-idle`.

**Likely cause:** In `handle_event`, `OnBattery` only sets `self.on_battery` and does **not** call `recreate_notifications()`. Timers are built at startup (default `on_battery = false` → AC policy) and only rebuilt on config/screensaver-inhibit changes. So if a recreate happens while on battery, the battery timeout stays armed after plugging in AC.

**Workaround:** set battery auto-suspend to Never as well.

Happy to test a patch that calls `recreate_notifications()` on `OnBattery` (and/or reads initial `OnBattery` at startup).
